Added ESLint linebreak issue
chingu-voyage3/bears-17 pull request #27
Opened 2017-12-07 13:56 UTC by Heyjp

2017-12-07 18:57 UTC, zsoltime requested changes
Could you check my comments and fix these issues? Thanks 😃

2017-12-07 18:57 UTC, zsoltime commented on README.md
> +### Developer Issues
It should be an `h4` tag so there should be four pound-signs/hashtags. Also "issues" should not be capitalised to match other `h4`s.

2017-12-07 18:57 UTC, zsoltime commented on README.md
> +To fix simply add the to bash the [following](https://gist.github.com/RadValentin/dd8b9d70448413301e9a274ed54661a5).
There is a typo there.

2017-12-07 20:07 UTC, Heyjp commented
Changed to h4, also couldn't see typo you were referring to though.

2017-12-08 07:43 UTC, zsoltime approved these changes
Great, thanks. 👍

2017-12-08 07:44 UTC, merged