Add tests for avatar component
chingu-voyage3/bears-17 pull request #60
Opened 2017-12-15 19:02 UTC by OStefani

2017-12-15 19:16 UTC, zsoltime requested changes
Great job, I had one issue with your last test, though. Check my previous comment.

2017-12-15 19:16 UTC, zsoltime commented on client/tests/components/Avatar.test.jsx
> +    const avatar = shallow(<Avatar />);
You should test the `img` prop here, so the component should have one like `<Avatar img="test" />`.

2017-12-16 12:03 UTC, OStefani commented
The last test is fixed.

2017-12-16 16:17 UTC, zsoltime approved these changes

2017-12-16 16:18 UTC, merged