Add query pagination and limit for get questions
chingu-voyage3/bears-17 pull request #64
Opened 2017-12-19 16:37 UTC by pchalubinska

Added query string for pagination and created a limit on results. Created a new function to return all results.

2017-12-19 18:03 UTC, zsoltime requested changes

2017-12-19 18:03 UTC, zsoltime commented on server/controller/index.js
> +exports.getAllQuestions = async (ctx) => {
We don't need two controllers for this, as we should never return every questions without a limit.

2017-12-19 18:03 UTC, zsoltime commented on server/controller/index.js
> +  const limit = 10;
We should also accept a `limit` through `ctx.request.query` with a default value of 10.

2017-12-19 18:03 UTC, zsoltime commented on server/controller/index.js
> +  const { page } = ctx.request.query;
We should check if `page` is a number and either return an error message or revert to a default value of 1 maybe?

2017-12-19 18:03 UTC, zsoltime commented on server/index.js
> +  .get('/api/all-questions', QuestionController.getAllQuestions);
We don't need this one.

2017-12-20 15:28 UTC, zsoltime approved these changes
Great job, @pchalubinska ;) Extra brownie points for checking the `res.length` 👍

2017-12-20 15:30 UTC, zsoltime commented
@pchalubinska, I've just noticed that there is a merge conflict. It's really easy to solve. Do you want me to fix this, or will you give it a go?

2017-12-20 16:17 UTC, pchalubinska commented
Yes I'll try:)

2017-12-20 16:31 UTC, pchalubinska commented
I removed the hardcoded limit(10) which we don't need anymore. I think that solves the conflicts?

2017-12-20 16:33 UTC, merged

2017-12-20 16:34 UTC, zsoltime commented
It does, thank you @pchalubinska :) It closes #56 and #57.