Upvote question (closes #54)
chingu-voyage3/bears-17 pull request #70
Opened 2017-12-21 00:37 UTC by zsoltime

I haven't added tests yet as I'm waiting for my other PR (#68) to be accepted first.

2017-12-21 10:41 UTC, Heyjp reviewed
Commented on the wrong PR 😂 

At the moment we are returning an array of user_id's is it possible that we instead have mongoose just return a count of the length of the array in place of that array? I think that voting should be anonymous at least to other users.

2017-12-21 10:46 UTC, zsoltime commented
And I was wondering why I can't send my response 😃 

Anyway, I need to check if we can display the length of the array, in that case we don't even need to have a `votes` field with the number of votes. We only need to know two things on the front end; if the user has voted already and the number of votes. I'll look into this, but any help is appreciated. 😄

2017-12-21 11:17 UTC, Heyjp commented
So this will return an object with just the counted votes. You can add and remove fields by just listing that field as either `0` or `1`.

```
exports.vote = async (ctx) => {

 await Answer.aggregate([{ $match: { _id: ObjectId(ctx.params.id) } },
    {
      $project: {
        _id: 0,
        votes: { $size: '$voted_by' },
      },
    },
  ]).then((res) => {
    console.log(res, "this is res");
    ctx.body = res[0];
    return res;
  });
}
```

2017-12-21 11:24 UTC, zsoltime commented
So you can use the mongo aggregation framework with Mongoose? That's great, thanks a lot 😃

2017-12-22 08:05 UTC, Heyjp commented
Branch has conflicts before it can be merged.

2018-01-08 16:12 UTC, zsoltime commented
@Heyjp Fixed, and added tests

2018-01-10 13:35 UTC, Heyjp requested changes
Just the one comment about the use of async. The rest works well.

2018-01-10 13:35 UTC, Heyjp commented on server/controller/answers.js
> +    .then(async (res) => {
I don't think async needs to be here. You could simply return `Answer.findOneAndUpdate` and do another `.then()` call as the function is already waiting for `Answer.findOne` to resolve.

2018-01-15 14:14 UTC, Heyjp commented
Going to merge this anyway now and review it later.

2018-01-15 14:14 UTC, Heyjp approved these changes

2018-01-15 14:14 UTC, merged