Flag answers as spam (closes #53)
chingu-voyage3/bears-17 pull request #71
Opened 2017-12-21 00:50 UTC by zsoltime

I haven't added tests yet as I'm waiting for my other PR (#68) to be accepted first.

2017-12-21 12:34 UTC, faityworld requested changes

2017-12-21 12:34 UTC, faityworld commented on server/models/answer.js
> +    flagged_by: { type: Array, default: [] },
The default is not necessary. We should use it for set up default values. But the array is empty.

2017-12-21 16:02 UTC, zsoltime commented on server/models/answer.js
> +    flagged_by: { type: Array, default: [] },
You're right, I've removed that. Thanks :)

2017-12-22 00:51 UTC, zsoltime commented
And finally added the tests too 😃

2017-12-22 07:44 UTC, faityworld approved these changes
Looks good

2017-12-22 07:44 UTC, merged